### ISSUE TITLE
Tutorial to push to Online Store from Databricks

### ISSUE THREAD

**Issue by amithadiraju1694** [logicalclocks/hopsworks-tutorials#102]
Hello ,

Sorry for a naive question. I want to use open source Hopsworks Feature Store, as a stand alone package, in Databricks clusters. Though I was able to find tutorials on how to connect to and save data in offline HSFS from here: [Hopsworks Examples](https://examples.hopsworks.ai/master/featurestore/databricks/featurestorequickstartdatabricksazure/) ; I'm struggling to find a similar one on how to push data in off-line feature store, to online feature store ( RonDB ).

Please provide appropriate directions. 

Thanks for your time ! !

**Comment by davitbzh** [comment]
Hi @amithadiraju1694 If you already connected and saved offline fg from Databricks then  just set `online_enabled=True`:
```
house_sale_fg = fs.create_feature_group("houses_for_sale_featuregroup",
                       version=1,
                       description="aggregate features of houses for sale per area",
                       primary_key=['area_id'],
                       online_enabled=True,
                       statistics_config={"histograms": True, "correlations": True, "exact_uniqueness": True})

house_sale_fg.save(houses_for_sale_features_df)
```

Please let me know if that worked

**Comment by amithadiraju1694** [comment]
> Hi @amithadiraju1694 If you already connected and saved offline fg from Databricks then just set `online_enabled=True`:
> 
> ```
> house_sale_fg = fs.create_feature_group("houses_for_sale_featuregroup",
>                        version=1,
>                        description="aggregate features of houses for sale per area",
>                        primary_key=['area_id'],
>                        online_enabled=True,
>                        statistics_config={"histograms": True, "correlations": True, "exact_uniqueness": True})
> 
> house_sale_fg.save(houses_for_sale_features_df)
> ```
> 
> Please let me know if that worked

Hey @davitbzh  Thanks for directions. I'm actually looking for a full-blown tutorial, to set up HSFS as a stand alone package ( like say feast ) in data bricks, how to configure a off-line store and how to push data from offline to online. I struggled to find one yet ( I may be looking at wrong places ). Please provide one if possible.

**Comment by davitbzh** [comment]
@amithadiraju1694 here is documentation how to connect Hopsworks Featurestore from databricks https://docs.hopsworks.ai/3.0/user_guides/integrations/databricks/configuration/. Please let me know if this is clear enough
