### ISSUE TITLE
H&M tutorials notebooks

### ISSUE THREAD

**Issue by riyaj8888** [logicalclocks/hopsworks-tutorials#190]
Hi, 
I am going through this video https://www.youtube.com/watch?v=9vBRjGgdyTY

but i couldn't find the resources mentioned in the video .
can u point out to those resources?

thanks

**Comment by davitbzh** [comment]
Hi,

you can find that tutorial in this branch https://github.com/logicalclocks/hopsworks-tutorials/tree/rec. Please note that you need managed hopsworks for this tutorial to work

**Comment by davitbzh** [comment]
tutorial is now available
