### ISSUE TITLE
Fraud batch training pipeline part2

### ISSUE THREAD

**Issue by danielakerberg** [logicalclocks/hopsworks-tutorials#203]
Hi,

I'm looking into your tutorial of Fraud batch training pipeline. I get an error at part 2 when trying to create the training dataset. I would be thankful for help.  /Daniel

Copy of code and error message:

TEST_SIZE = 0.2
​
td_version, td_job = feature_view.create_train_test_split(
    description = 'transactions fraud batch training dataset',
    data_format = 'csv',
    test_size = TEST_SIZE,
    write_options = {'wait_for_job': True}
)
​
---------------------------------------------------------------------------
RestAPIError                              Traceback (most recent call last)
<ipython-input-12-83ddaa9adfa8> in <module>
      1 TEST_SIZE = 0.2
      2 
----> 3 td_version, td_job = feature_view.create_train_test_split(
      4     description = 'transactions fraud batch training dataset',
      5     data_format = 'csv',

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/feature_view.py in create_train_test_split(self, test_size, train_start, train_end, test_start, test_end, storage_connector, location, description, extra_filter, data_format, coalesce, seed, statistics_config, write_options)
   1038         )
   1039         # td_job is used only if the python engine is used
-> 1040         td, td_job = self._feature_view_engine.create_training_dataset(
   1041             self, td, write_options
   1042         )

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/core/feature_view_engine.py in create_training_dataset(self, feature_view_obj, training_dataset_obj, user_write_options)
    239     ):
    240         self._set_event_time(feature_view_obj, training_dataset_obj)
--> 241         updated_instance = self._create_training_data_metadata(
    242             feature_view_obj, training_dataset_obj
    243         )

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/core/feature_view_engine.py in _create_training_data_metadata(self, feature_view_obj, training_dataset_obj)
    501 
    502     def _create_training_data_metadata(self, feature_view_obj, training_dataset_obj):
--> 503         td = self._feature_view_api.create_training_dataset(
    504             feature_view_obj.name, feature_view_obj.version, training_dataset_obj
    505         )

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/core/feature_view_api.py in create_training_dataset(self, name, version, training_dataset_obj)
    175         headers = {"content-type": "application/json"}
    176         return training_dataset_obj.update_from_response_json(
--> 177             self._client._send_request(
    178                 "POST", path, headers=headers, data=training_dataset_obj.json()
    179             )

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/decorators.py in if_connected(inst, *args, **kwargs)
     33         if not inst._connected:
     34             raise NoHopsworksConnectionError
---> 35         return fn(inst, *args, **kwargs)
     36 
     37     return if_connected

/srv/hops/anaconda/envs/theenv/lib/python3.8/site-packages/hsfs/client/base.py in _send_request(self, method, path_params, query_params, headers, data, stream, files)
    169 
    170         if response.status_code // 100 != 2:
--> 171             raise exceptions.RestAPIError(url, response)
    172 
    173         if stream:

RestAPIError: Metadata operation error: (url: https://hopsworks.glassfish.service.consul:8182/hopsworks-api/api/project/1155/featurestores/1103/featureview/transactions_view_fraud_batch_fv/version/1/trainingdatasets). Server response: 
HTTP code: 500, HTTP reason: Internal Server Error, body: b'{"type":"restApiJsonResponse","errorCode":120000,"errorMsg":"A generic error occurred."}', error code: 120000, error msg: A generic error occurred., user msg:

**Comment by davitbzh** [comment]
we have just updated tutorials please try it again. If you still experience the issue please post on hopsworks slack chanel
